### ISSUE TITLE
Hey Chris

### ISSUE THREAD

**Issue by sammarshall61** [ChrisRisner/feedback#10]
You're the man when it come to mobile services and I have a question for you, if you could help you'd be my hero. I'm trying to create a custom API that filters a table by a list of items I have sent in the body. Let's say I send the item = ['a','b','c'] in the body, I want my custom api to return all items that have the value 'a', 'b', or 'c' in the type column. Is there a good way to do this? Best Sam

**Comment by ChrisRisner** [comment]
So sorry for not having seen your issue.  Notifications were never set up properly so I wasn't aware.  Please reopen and let me know if I can still help or answer any questions.
