### ISSUE TITLE
Android Nav Drawer

### ISSUE THREAD

**Issue by power7714** [ChrisRisner/feedback#15]
Thank you for your Nav Drawer example. I have a quick question. I have a MainActivity with a nav drawer. I've set a default fragment. When I click the devices built-in hardware/software back button, the primary fragment just refreshes rather than the app closing. How can I ensure the app closes rather than refreshing the primary fragment? Thank you in advance.

**Comment by ChrisRisner** [comment]
Your best bet would be to override the functionality of the back button and then call finish on your activity.
