### ISSUE TITLE
Questions on Azure Mobile 

### ISSUE THREAD

**Issue by willysharp5** [ChrisRisner/feedback#2]
Hey Chris,
Saw your talk about Azure Mobile Services. I would like to use Azure for my mobile app in Andriod and IOS. I am also evaluating AWS mobile services but find that their documentation is more lacking and 

I have extensive experience using Parse and have found it lacking in backend scripting cloud jobs and extension of certain services like machine learning. 

I have gone through a lot of the documentation and videos tuts on azure mobile. I feel like it a fire hose of information. 

A couple of things I would like to achieve and would love to get some help from you in any way you can, pointing me to docs online or code snippets.

IOS Swift
1. Build a IOS app using Swift and Azure Mobile services
2. Authentication using Gmail and Custom Authentication with Password reset Functionality 
3. Database with relationships and a somewhat complex joins 
4. Running Backend jobs 
5. Backend script that modifies data before submission to database
6. Machine learning particularly the Predictive piece and how would I tie that to a mobile service or app
7. IOS TablesView that has infinite scrolling or paging
8. Sending and receiving emails 
9. Push notification
10. Dealing with images, uploading/downloading 

Andriod Studio
Same as above just an android version 

I understand there isn't a complete template and code for all these but if you could point me to code or git repositories that would be very very helpful. I have found a good amount of these information scattered around the web, while some are old info in objective C and some are old versions of Azure. Information is scattered around.

**Comment by ChrisRisner** [comment]
So sorry for not having seen your issue.  Notifications were never set up properly so I wasn't aware.  Please reopen and let me know if I can still help or answer any questions.
