### ISSUE TITLE
MobileServiceClient

### ISSUE THREAD

**Issue by adrianboston** [ChrisRisner/feedback#3]
Chris,

You have written one of the first Android examples of using Azure Mobile Services -- well before the introduction of the MobileServiceClient class.

I'm seeking a semi-complex example of using the MobileServiceClient across a number of Activities and the use of multiple sync tables with local storage in SQLLite. The current Todo example is just not cutting it as it is one screen and one class. Your TodosFetchService class uses an IntentService so suprisingly it might be the best example there is to date but its confusing with all the older HttpURLConnection. Presumably the new MobileServiceClient wraps up that jazz.

Please point me to an update version of something with a few views and a few tables.

Thank you sir,
Adrian
adrian@upsidecommerce.com

**Comment by ChrisRisner** [comment]
So sorry for not having seen your issue.  Notifications were never set up properly so I wasn't aware.  Please reopen and let me know if I can still help or answer any questions.
