### ISSUE TITLE
Lens Rocket Code

### ISSUE THREAD

**Issue by sammarshall61** [ChrisRisner/feedback#4]
Hey Chris,

I've found looking at your Lens Rocket code in the past to be really helpful while learning Azure Mobile Services. I was looking today and saw the code was taken down, has the repo been moved or is there someway I can stiil use it as reference?

Best,

Sam

**Comment by DarkNormal** [comment]
+1
I'd really love to take a look at the Android source code for Lens Rocket to see your techniques with Mobile Services, specifically authentication, as the repository is gone/moved.

**Comment by ChrisRisner** [comment]
Sorry about this.  There was a shift in what repos were showing up in that org and no one notified me.  Plus I never received an alert on this issue so my response is terribly delayed.  You can find the repos here:

https://github.com/Microsoft/Android-LensRocket
https://github.com/Microsoft/iOS-LensRocket
