### ISSUE TITLE
iOS - saving images to Azure Storage via Mobile Services

### ISSUE THREAD

**Issue by egrimmius** [ChrisRisner/feedback#5]
What happened to the repository 'iOS-MobileServices-Storage' you reference on your website?  I'm trying to add the ability to save images to my Azure Mobile Services backed iOS app.  Thanks.

**Comment by ChrisRisner** [comment]
Links should now redirect to where it was moved: https://github.com/ChrisRisner/iOS-MobileServices-Storage
