### ISSUE TITLE
Need help in Setting up the HockeyApp Task for Windows.

### ISSUE THREAD

**Issue by SrivatsaMarichi** [ChrisRisner/feedback#6]
Hi Chris,

I would like to get your help in setting up hockeyApp Task with VSO build agent. Ending up with some errors. Would be glad if you could help me out with.

Thanks in advance,
Srivatsa

**Comment by ChrisRisner** [comment]
So sorry for not having seen your issue.  Notifications were never set up properly so I wasn't aware.  Please reopen and let me know if I can still help or answer any questions.
