### ISSUE TITLE
Study on Exception Handling in Android App Development

### ISSUE THREAD

**Issue by diogoqueiroz** [ChrisRisner/feedback#7]
Hi there, Chris Risner!

We are Software Engineering researchers who are interested in understanding the best practices applied when developing exception handling code for Android apps.

We are contacting you because you have been identified as one of the experts in Android development in mobile conferences, author of books about Android and/or well-referenced blogs about Android. We believe you can strongly contribute to this study and we would appreciate your feedback via this 15-minute survey.

Here's a link to the survey: 
https://docs.google.com/forms/d/1_isE7nQ8QRrdeKkqBRTY0OvJPrYmNOxDNvxOnqyD1Y4/viewform?usp=send_form

This is a purely academic study which aims at extending the work presented this year at 12th IEEE/ACM Working Conference on Mining Software Repositories - Unveiling Exception Handling Bug Hazards in Android Based on GitHub and Google Code Issues (http://2015.msrconf.org/program.php).

We would appreciate if you could send this survey to other Android experts that you think can also help with this study.

Many thanks in advance,
Diogo Queiroz and Roberta Coelho
------------------------------------------------------------------
Computer Science Department
Federal University of Rio Grande do Norte, Brazil

**Comment by ChrisRisner** [comment]
Looks like I was too late.  Sorry about that.
