### ISSUE TITLE
JDXA ORM for Android

### ISSUE THREAD

**Issue by dperiwal** [ChrisRisner/feedback#8]
Hello Chris,

I am the founder of Software Tree, a company with a mission to simplify data integration. We specialize in Object Relational Mapping (ORM) technology having produced innovative ORM products like JDX for Java, NJDX for .NET, and JDXA for Android.

I wanted to meet with you at AnDevCon 2015 in Santa Clara, CA yesterday morning but, due to unavoidable reasons, could not make it for your presentation on the topic of “Going Offline with Android and Azure Mobile Apps”.  I wanted to explore if our recently released [JDXA ORM for Android](http://www.softwaretree.com/v1/products/jdxa/jdxa.html) can help simplify the persistence mechanism in your offline SDK. Anyway, please let me know your email address so that I can send you more details about JDXA and we can talk further.

Thanks,

-- Damodar Periwal
Founder
[Software Tree](http://www.softwaretree.com)
dperiwal@softwaretree.com
408-282-3606

**Comment by ChrisRisner** [comment]
So sorry for not having seen your issue.  Notifications were never set up properly so I wasn't aware.  Please reopen and let me know if I can still help or answer any questions.
