### ISSUE TITLE
Opencv-AndroidStdio-Parse.com

### ISSUE THREAD

**Issue by kenanklc** [ChrisRisner/feedback#9]
I'm developing an OpenCV project with javascript and also I'm developing its mobile interface in Android. My purpose is to compare plant pictures and decide their species.Researchers who use Android application will take plant photos and upload them (such as 'tree leaf photo'). I intent to execute comparison algorithms in the cloud. I use Parse as mobile database so I thought that I could use Cloud Code in Parse to run my Javascript codes. Can I do this ? Help me please ..

**Comment by ChrisRisner** [comment]
I don't really have much expertise when it comes to Parse.  However, since it's been shut down, I'd look at Azure Mobile Apps.  Sorry for the delay in responding.
